target: LAIONOCRDataset
params:

  data_root: '/data/zhaoym/TextDesign-XL'

  H: 512
  W: 512
  word_len: [1, 12]
  seq_len: 12
  mask_min_ratio: 0.01
  seg_min_ratio: 0.001
  aug_text_enabled: True
  aug_text_ratio: 1.0

  use_cached: True
  length: 100000