type: "demo"

# path
load_ckpt_path: "./checkpoints/st-step=100000+la-step=100000-v1.ckpt"  #512-inpainting-ema.ckpt
model_cfg_path: "./configs/test/textdesign_sd_2.yaml"  #sd_2_inpainting.yaml

# param
H: 512
W: 512
seq_len: 12
batch_size: 1

channel: 4 # AE latent channel
factor: 8 # AE downsample factor
scale: [4.0, 0.0] # content scale, style scale
noise_iters: 10
force_uc_zero_embeddings: ["ref", "label"]
aae_enabled: False
detailed: True
dual_conditioner: False


# runtime
steps: 50
init_step: 0
num_workers: 0
gpu: 4
max_iter: 100

